language: php

php:
  - 5.6
  - 7.0
  - 7.2

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=^4
  - SYMFONY_VERSION=dev-master

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-dist --no-interaction

script: vendor/bin/phpunit

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
  exclude:
    - env: SYMFONY_VERSION=dev-master
      php: 5.6
    - env: SYMFONY_VERSION=dev-master
      php: 7.0
    - env: SYMFONY_VERSION=^4
      php: 5.6
    - env: SYMFONY_VERSION=^4
      php: 7.0
